package com.dida.common.util

object DIDAINTENT {
    const val EXTRA_PUSH_MESSAGE = "PUSH_MESSAGE"
    const val REQUEST_KEY_SUCCESS_SIGNUP = "RESULT_KEY_SUCCESS_SIGNUP"

    const val RESULT_KEY_UPDATE_PROFILE = "RESULT_KEY_UPDATE_PROFILE"
    const val RESULT_KEY_SUCCESS_SIGNUP = "RESULT_KEY_SUCCESS_SIGNUP"
    const val RESULT_KEY_POST_NOTIFICATION_PERMISSION_GRANTED = "RESULT_KEY_POST_NOTIFICATION_PERMISSION_GRANTED"

    const val COMMUNITY_SCREEN = "COMMUNITY_SCREEN"
    const val REPORT = "REPORT"
    const val BLOCK = "BLOCK"
    const val CREATE = "CREATE"
}