package com.dida.common.util

object DIDAINTENT {
    const val RESULT_KEY_UPDATE_PROFILE = "RESULT_KEY_UPDATE_PROFILE"

    const val RESULT_SCREEN_COMMUNITY = "RESULT_SCREEN_COMMUNITY"

    const val RESULT_KEY_POST_REPORT = "RESULT_KEY_POST_REPORT"
    const val RESULT_KEY_USER_REPORT = "RESULT_KEY_USER_REPORT"
    const val RESULT_KEY_CARD_REPORT = "RESULT_KEY_CARD_REPORT"

    const val RESULT_KEY_USER_BLOCK = "RESULT_KEY_USER_BLOCK"
    const val RESULT_KEY_POST_BLOCK = "RESULT_KEY_POST_BLOCK"
    const val RESULT_KEY_CARD_BLOCK = "RESULT_KEY_CARD_BLOCK"

    const val RESULT_KEY_CREATE = "RESULT_KEY_CREATE"
}